"""initial schema

Revision ID: 8adb96b11705
Revises: 
Create Date: 2026-06-05 10:32:45.117578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8adb96b11705'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_types',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_per_day', sa.Integer(), nullable=False),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dimensions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_available_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='bookingstatus'), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_venue_id'), ['venue_id'], unique=False)
        batch_op.create_index('uq_booking_confirmed_per_day', ['venue_id', 'date'], unique=True, postgresql_where=sa.text("status = 'confirmed'"), sqlite_where=sa.text("status = 'confirmed'"))

    op.create_table('event_type_translations',
    sa.Column('event_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.PrimaryKeyConstraint('event_type_id', 'locale')
    )
    op.create_table('quote_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('venue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'closed', name='quotestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quote_requests_venue_id'), ['venue_id'], unique=False)

    op.create_table('venue_amenities',
    sa.Column('venue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amenity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'amenity_id')
    )
    op.create_table('venue_amenity_translations',
    sa.Column('venue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amenity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compact_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detailed_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'amenity_id', 'locale')
    )
    op.create_table('venue_available_dates',
    sa.Column('venue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'date')
    )
    op.create_table('venue_event_types',
    sa.Column('venue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'event_type_id')
    )
    op.create_table('venue_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venue_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_images_venue_id'), ['venue_id'], unique=False)

    op.create_table('venue_translations',
    sa.Column('venue_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cancellation_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'locale')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_translations')
    with op.batch_alter_table('venue_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_images_venue_id'))

    op.drop_table('venue_images')
    op.drop_table('venue_event_types')
    op.drop_table('venue_available_dates')
    op.drop_table('venue_amenity_translations')
    op.drop_table('venue_amenities')
    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quote_requests_venue_id'))

    op.drop_table('quote_requests')
    op.drop_table('event_type_translations')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('uq_booking_confirmed_per_day', postgresql_where=sa.text("status = 'confirmed'"), sqlite_where=sa.text("status = 'confirmed'"))
        batch_op.drop_index(batch_op.f('ix_bookings_venue_id'))

    op.drop_table('bookings')
    op.drop_table('venues')
    op.drop_table('event_types')
    op.drop_table('amenities')
    # ### end Alembic commands ###
